'''
Input constant value for the 
numerical buttons
'''
NUMBER_BUTTON_ZERO_VALUE       = 0
NUMBER_BUTTON_ONE_VALUE        = 1
NUMBER_BUTTON_TWO_VALUE        = 2
NUMBER_BUTTON_THREE_VALUE      = 3
NUMBER_BUTTON_FOUR_VALUE       = 4
NUMBER_BUTTON_FIVE_VALUE       = 5
NUMBER_BUTTON_SIX_VALUE        = 6
NUMBER_BUTTON_SEVEN_VALUE      = 7
NUMBER_BUTTON_EIGHT_VALUE      = 8
NUMBER_BUTTON_NINE_VAULE       = 9

NO_PRE_INPUT_NUM_VALUE        = -1

OPERATION_BUTTON_ADDITION_STRING = "+"
OPERATION_BUTTON_SUBTRACTION_STRING = "-"
OPERATION_BUTTON_MULTIPLICATION_STRING = "x"
OPERATION_BUTTON_DIVISON_STRING = "-"
OPERATION_BUTTON_SOLUTION_STRING = "="

